# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/p/fm3/fm3.srcs/sources_1/bd/design_1/ip/design_1_axi_dotprod_4_0_0/design_1_axi_dotprod_4_0_0.xci
# IP: The module: 'design_1_axi_dotprod_4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx/p/fm3/fm3.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_axi_dotprod_4_0_0/design_1_axi_dotprod_4_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dotprod_4_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/p/fm3/fm3.srcs/sources_1/bd/design_1/ip/design_1_axi_dotprod_4_0_0/design_1_axi_dotprod_4_0_0.xci
# IP: The module: 'design_1_axi_dotprod_4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx/p/fm3/fm3.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_axi_dotprod_4_0_0/design_1_axi_dotprod_4_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dotprod_4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
