# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/p/fm3/fm3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2.xci
# IP: The module: 'design_1_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d || ORIG_REF_NAME==bd_378d} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_1/bd_378d_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_g_inst_0 || ORIG_REF_NAME==bd_378d_g_inst_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_2/bd_378d_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_aw_0 || ORIG_REF_NAME==bd_378d_slot_0_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_3/bd_378d_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_w_0 || ORIG_REF_NAME==bd_378d_slot_0_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_4/bd_378d_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_b_0 || ORIG_REF_NAME==bd_378d_slot_0_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_5/bd_378d_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_ar_0 || ORIG_REF_NAME==bd_378d_slot_0_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_6/bd_378d_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_r_0 || ORIG_REF_NAME==bd_378d_slot_0_r_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_7/bd_378d_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_aw_0 || ORIG_REF_NAME==bd_378d_slot_1_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_8/bd_378d_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_w_0 || ORIG_REF_NAME==bd_378d_slot_1_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_9/bd_378d_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_b_0 || ORIG_REF_NAME==bd_378d_slot_1_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_10/bd_378d_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_ar_0 || ORIG_REF_NAME==bd_378d_slot_1_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_11/bd_378d_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_r_0 || ORIG_REF_NAME==bd_378d_slot_1_r_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_12/bd_378d_slot_4_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_aw_0 || ORIG_REF_NAME==bd_378d_slot_4_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_13/bd_378d_slot_4_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_w_0 || ORIG_REF_NAME==bd_378d_slot_4_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_14/bd_378d_slot_4_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_b_0 || ORIG_REF_NAME==bd_378d_slot_4_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_15/bd_378d_slot_4_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_ar_0 || ORIG_REF_NAME==bd_378d_slot_4_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_16/bd_378d_slot_4_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_r_0 || ORIG_REF_NAME==bd_378d_slot_4_r_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_17/bd_378d_slot_5_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_aw_0 || ORIG_REF_NAME==bd_378d_slot_5_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_18/bd_378d_slot_5_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_w_0 || ORIG_REF_NAME==bd_378d_slot_5_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_19/bd_378d_slot_5_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_b_0 || ORIG_REF_NAME==bd_378d_slot_5_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_20/bd_378d_slot_5_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_ar_0 || ORIG_REF_NAME==bd_378d_slot_5_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_21/bd_378d_slot_5_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_r_0 || ORIG_REF_NAME==bd_378d_slot_5_r_0} -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0_ooc.xdc

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d_ooc.xdc

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/p/fm3/fm3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2.xci
# IP: The module: 'design_1_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d || ORIG_REF_NAME==bd_378d} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_1/bd_378d_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_g_inst_0 || ORIG_REF_NAME==bd_378d_g_inst_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_2/bd_378d_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_aw_0 || ORIG_REF_NAME==bd_378d_slot_0_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_3/bd_378d_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_w_0 || ORIG_REF_NAME==bd_378d_slot_0_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_4/bd_378d_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_b_0 || ORIG_REF_NAME==bd_378d_slot_0_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_5/bd_378d_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_ar_0 || ORIG_REF_NAME==bd_378d_slot_0_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_6/bd_378d_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_0_r_0 || ORIG_REF_NAME==bd_378d_slot_0_r_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_7/bd_378d_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_aw_0 || ORIG_REF_NAME==bd_378d_slot_1_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_8/bd_378d_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_w_0 || ORIG_REF_NAME==bd_378d_slot_1_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_9/bd_378d_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_b_0 || ORIG_REF_NAME==bd_378d_slot_1_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_10/bd_378d_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_ar_0 || ORIG_REF_NAME==bd_378d_slot_1_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_11/bd_378d_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_1_r_0 || ORIG_REF_NAME==bd_378d_slot_1_r_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_12/bd_378d_slot_4_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_aw_0 || ORIG_REF_NAME==bd_378d_slot_4_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_13/bd_378d_slot_4_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_w_0 || ORIG_REF_NAME==bd_378d_slot_4_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_14/bd_378d_slot_4_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_b_0 || ORIG_REF_NAME==bd_378d_slot_4_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_15/bd_378d_slot_4_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_ar_0 || ORIG_REF_NAME==bd_378d_slot_4_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_16/bd_378d_slot_4_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_4_r_0 || ORIG_REF_NAME==bd_378d_slot_4_r_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_17/bd_378d_slot_5_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_aw_0 || ORIG_REF_NAME==bd_378d_slot_5_aw_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_18/bd_378d_slot_5_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_w_0 || ORIG_REF_NAME==bd_378d_slot_5_w_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_19/bd_378d_slot_5_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_b_0 || ORIG_REF_NAME==bd_378d_slot_5_b_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_20/bd_378d_slot_5_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_ar_0 || ORIG_REF_NAME==bd_378d_slot_5_ar_0} -quiet] -quiet

# IP: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_21/bd_378d_slot_5_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_slot_5_r_0 || ORIG_REF_NAME==bd_378d_slot_5_r_0} -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0_ooc.xdc

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d_ooc.xdc

# XDC: c:/Xilinx/p/fm3/fm3.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
